on:
  push:
    branches: [staging, prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.18.2 to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - name: Setup environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "DEV_SECRET=${{ secrets.DEPLOY_USER }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "PROD_SECRET=${{ secrets.DEPLOY_USER }}" >> $GITHUB_ENV
          fi
      - name: test console environment
        run: |
          echo "vari---------${{ env.DEV_SECRET }}"
      - name: Create .env file from CONFIG_ENV_CONTENT
        run: |
          echo "${{ secrets.CONFIG_ENV_CONTENT }}" > .env
      - run: npm install
      - run: CI=false npm run build
      - name: ssh deploy on aws  lightsail
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          SOURCE: "build/*"
          TARGET: ${{ secrets.DEPLOY_TARGET }}
