on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.18.2 to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - name: Create .env file from CONFIG_ENV_CONTENT
        run: |
          echo "${{ secrets.CONFIG_ENV_CONTENT }}" > .env
      - run: npm install
      - run: CI=false npm run build
      - name: Deploy to Ubuntu Server www
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "build/*"
          target: ${{ secrets.DEPLOY_TARGET }}
          rm: true
          strip_components: 1
