on:
  push:
    branches: [staging, prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.18.2 to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - name: Setup environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "DEPLOY_USER=${{ secrets.STG_DEPLOY_USER }}" >> $GITHUB_ENV
            echo "DEPLOY_PORT=${{ secrets.STG_DEPLOY_PORT }}" >> $GITHUB_ENV
            echo "DEPLOY_KEY=${{ secrets.STG_DEPLOY_KEY }}" >> $GITHUB_ENV
            echo "CONFIG_ENV_CONTENT=${{ secrets.STG_CONFIG_ENV_CONTENT }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "PROD_SECRET=${{ secrets.DEPLOY_USER }}" >> $GITHUB_ENV
          fi
      - name: Create .env file from CONFIG_ENV_CONTENT
        run: |
          echo "${{ env.CONFIG_ENV_CONTENT }}" > .env
      - run: npm install
      - run: CI=false npm run build
      - name: ssh deploy on aws  lightsail
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ env.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ env.DEPLOY_USER }}
          REMOTE_PORT: ${{ env.DEPLOY_PORT }}
          SOURCE: "build/*"
          TARGET: ${{ secrets.DEPLOY_TARGET }}
